name: Gitleaks Secrets Scan for DevOpsWorkshopProject-Parent master branch

on:
  push:
    branches:
      - '**'
      
  workflow_call:
  schedule:
      - cron: '0 9 * * *'  # This cron expression runs at 9 AM UTC every day

jobs:
  check-for-secrets:
    uses: minutuscomputing/Gitleaks-Checker/.github/workflows/Gitleaks-Checker.yml@main
    secrets:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
