name: Gitleaks Secrets Scan for DevOpsWorkshopProject-Parent soumya_ws branch

on:
  push:
    branches:
      - '**'
      
  workflow_call:
  schedule:
      - cron: '0 9 * * *'  # This cron expression runs at 9 AM UTC every day

jobs:
  check-for-secrets:
    uses: minutuscomputing/DevOpsWorkShopProject-Parent/.github/workflows/DevOpsWorkShopProject-Parent_master.yml@master
    secrets:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
